"""initial_schema

Revision ID: f3acf65a78ac
Revises: 
Create Date: 2026-04-27 01:12:54.474177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3acf65a78ac'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('areas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tipos_vehiculo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dni', sa.String(length=8), nullable=False),
    sa.Column('nombres', sa.String(length=100), nullable=False),
    sa.Column('apellidos', sa.String(length=100), nullable=False),
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.Column('cargo', sa.String(length=100), nullable=True),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.Column('telefono_wa', sa.String(length=9), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ),
    sa.ForeignKeyConstraint(['rol_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dni'),
    sa.UniqueConstraint('telefono_wa')
    )
    op.create_table('vehiculos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('placa', sa.String(length=10), nullable=False),
    sa.Column('tipo_id', sa.Integer(), nullable=False),
    sa.Column('capacidad_pasajeros', sa.Integer(), nullable=False),
    sa.Column('marca', sa.String(length=50), nullable=True),
    sa.Column('modelo', sa.String(length=50), nullable=True),
    sa.Column('anio', sa.Integer(), nullable=True),
    sa.Column('color', sa.String(length=30), nullable=True),
    sa.Column('soat_vencimiento', sa.Date(), nullable=False),
    sa.Column('estado_actual', sa.String(length=20), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['tipo_id'], ['tipos_vehiculo.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('placa')
    )
    op.create_table('conductores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('licencia_categoria', sa.String(length=10), nullable=True),
    sa.Column('licencia_numero', sa.String(length=20), nullable=True),
    sa.Column('licencia_vencimiento', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id')
    )
    op.create_table('cuentas_admin',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id')
    )
    op.create_table('asignaciones_transporte',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conductor_id', sa.Integer(), nullable=False),
    sa.Column('vehiculo_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('hora_salida', sa.Time(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['conductor_id'], ['conductores.id'], ),
    sa.ForeignKeyConstraint(['vehiculo_id'], ['vehiculos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tickets_salida',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('solicitante_id', sa.Integer(), nullable=False),
    sa.Column('aprobador_jefe_id', sa.Integer(), nullable=True),
    sa.Column('aprobador_rrhh_id', sa.Integer(), nullable=True),
    sa.Column('asignacion_id', sa.Integer(), nullable=False),
    sa.Column('destino', sa.String(length=200), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['aprobador_jefe_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['aprobador_rrhh_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['asignacion_id'], ['asignaciones_transporte.id'], ),
    sa.ForeignKeyConstraint(['solicitante_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bitacora_eventos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('registrado_por', sa.Integer(), nullable=False),
    sa.Column('tipo_accion', sa.String(length=30), nullable=False),
    sa.Column('fecha_hora', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['registrado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets_salida.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bitacora_eventos')
    op.drop_table('tickets_salida')
    op.drop_table('asignaciones_transporte')
    op.drop_table('cuentas_admin')
    op.drop_table('conductores')
    op.drop_table('vehiculos')
    op.drop_table('usuarios')
    op.drop_table('tipos_vehiculo')
    op.drop_table('roles')
    op.drop_table('areas')
    # ### end Alembic commands ###
